// Generated by binpac_quickstart

#include "IKEv2.h"

#include "Reporter.h"

#include "types.bif.h"

#include "events.bif.h"

using namespace analyzer::IKEv2;

IKEv2_Analyzer::IKEv2_Analyzer(Connection* c)

: analyzer::Analyzer("IKEv2", c)

	{
	interp = new binpac::IKEv2::IKEv2_Conn(this);
	
	}

IKEv2_Analyzer::~IKEv2_Analyzer()
	{
	delete interp;
	}

void IKEv2_Analyzer::Done()
	{
	
	Analyzer::Done();
	
	}

void IKEv2_Analyzer::DeliverPacket(int len, const u_char* data,
	 			  bool orig, uint64 seq, const IP_Hdr* ip, int caplen)
	{
	
	Analyzer::DeliverPacket(len, data, orig, seq, ip, caplen);

	try
		{
		interp->NewData(orig, data, data + len);
		}
	catch ( const binpac::Exception& e )
		{
		ProtocolViolation(fmt("Binpac exception: %s", e.c_msg()));
		}
	}
