// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_IKEv2_IKEv2_H
#define ANALYZER_PROTOCOL_IKEv2_IKEv2_H

#include "events.bif.h"

#include "analyzer/protocol/udp/UDP.h"

#include "IKEv2_pac.h"

namespace analyzer { namespace IKEv2 {

class IKEv2_Analyzer

: public analyzer::Analyzer {

public:
	IKEv2_Analyzer(Connection* conn);
	virtual ~IKEv2_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverPacket(int len, const u_char* data, bool orig,
					uint64 seq, const IP_Hdr* ip, int caplen);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new IKEv2_Analyzer(conn); }

protected:
	binpac::IKEv2::IKEv2_Conn* interp;
	
};

} } // namespace analyzer::* 

#endif
